name: build-wheel

on:
  push:
    tags:
      - 'v*' # run on tag creation

permissions: { contents: write }

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with: 
          python-version: '3.12'

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build wheel
        uses: PyO3/maturin-action@v1
        with:
          args: |
            --manifest-path crates/py_binding/Cargo.toml
            --release
            --out dist
            --find-interpreter
          manylinux: auto

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist/*.whl

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with: 
          name: wheels-ubuntu-latest
          path: dist/linux
      - uses: actions/download-artifact@v4
        with:
          name: wheels-windows-latest
          path: dist/windows

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            dist/**/*

